### ISSUE TITLE
Error when no TS definition is in SysSettings

### ISSUE THREAD

**Issue by olejandro** [kanors-emr/Veda2.0-Installation#10]
Currently Veda throws an error when no TS definition is present in SysSettings. At the same time all seems to be working as long as a ts definition(s) is present in a scenario file(s). 

@akanudia

**Comment by akanudia** [comment]
Thanks for pointing this out. We will take care of this case.

**Comment by akanudia** [comment]
fixed in version 16

**Comment by rohitkanors** [comment]
This is still in testing and not included in version 16.

**Comment by rohitkanors** [comment]
Hi @olejandro, this is included and fixed in version 17.

**Comment by olejandro** [comment]
Seems the issue is back in the [latest](https://github.com/kanors-emr/Veda2.0-Installation/tree/8cbdd4430f1e2cc244c0ef391fd425087f357f64) version.
The following error is thrown: `P0001: TimeSlices table not found`
@rohitkanors @akanudia

**Comment by akanudia** [comment]
Please put a dummy TS def table in SysSettings till we resolve this.

**Comment by olejandro** [comment]
Ok, thanks @akanudia. It seems that, other than being thrown, the error is not causing any issue.
