### ISSUE TITLE
SolveTime reporting

### ISSUE THREAD

**Issue by olejandro** [kanors-emr/Veda2.0-Installation#33]
Currently the case manager reports SolveTime in HH:MM(?) format. What does it represent?
I have a case where `08:42` SolveTime is reported, but looking at the job log file from GAMS I see ca. 33 hours reported as time to complete the job.
Since the difference between the reported SolveTime and the value from GAMS is about 24 hours, could there be calculation error? Or is the difference due to something else being reported?

**Comment by akanudia** [comment]
Apologies for the delayed response. We were not able to reproduce the issue, which might have something to do with the regional settings of Windows. Can you please tell us the regional settings/timezone on the machine where you observed this issue?

**Comment by Antti-L** [comment]
To me what Olex reported looks very much like the timer had been reset to zero after 24 hrs (24 + 8:42 ≈ 33 hours), so a likely timer rollover issue.  Could such a rollover be somehow caused by regional settings/timezone?

**Comment by RahulKanors** [comment]
We've pinpointed the actual issue and devised a solution. It will be incorporated in the upcoming release.

**Comment by akanudia** [comment]
Addressed in version 3.1.1.

**Comment by SDockweiler** [comment]
Speaking of SolveTime reporting, it doesnt seem to ever show up in Veda when we run our models. Just updated to the new version (3.1.1.0) and it still isn't showing. 
![image](https://github.com/kanors-emr/Veda2.0-Installation/assets/168806410/52d76682-9828-4b02-8744-85ef932a97e5)

**Comment by RahulKanors** [comment]
Apologies for any inconvenience caused.
Could you kindly provide the logs and ".lst" file to [us](support@kanors.com)?

**Comment by RahulKanors** [comment]
> Speaking of SolveTime reporting, it doesnt seem to ever show up in Veda when we run our models. Just updated to the new version (3.1.1.0) and it still isn't showing. See image below of two finished runs. ![image](https://private-user-images.githubusercontent.com/168806410/327659850-52d76682-9828-4b02-8744-85ef932a97e5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU2MDQ2MTcsIm5iZiI6MTcxNTYwNDMxNywicGF0aCI6Ii8xNjg4MDY0MTAvMzI3NjU5ODUwLTUyZDc2NjgyLTk4MjgtNGIwMi04NzQ0LTg1ZWY5MzJhOTdlNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxM1QxMjQ1MTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00ZjA0NzUwNjgyYjdkODQ3MmQzN2Q5YjI4YmU0MDRlMTMxMjQ2Njc2MzM4ODA5M2RlYWUzNDhhM2ZkNGZiYTZlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.N-D2ITLjwSugU6uuYjAkKVZ5Di_7a9ON-Oge1oblWVg)

We've revised how solveTime is displayed in the "Runs Status" window, now using the '**casename**_run_log.txt' file instead of '**casename**.lst' in version 3.1.1.0. This update is compatible with GAMS version 32 and later.

As you are using GAMS version 29, solveTime will not be displayed with the latest version (3.1.10). Your choices are to stick with the prior version (3.0.7.0) or upgrade GAMS to version 32 or newer.

**Comment by Antti-L** [comment]
Can you also comment what might be the reason for the missing ModelStatus, SolverStatus and ObjectiveValue in SDockweiler's screenshot?  I assume they cannot be taken from the log file?
